version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

elixir-docker-template: &elixir-docker-template
  working_directory: ~/repo
  steps:
    - checkout
    - run: mix deps.get
    - run: mix deps.compile
    - run: mix test

jobs:
  test:
    <<: *elixir-docker-template
    docker:
      - image: circleci/elixir:1.4